# service-template-java/.github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    uses: vimsco-devops/platform-org/.github/workflows/reusable-ci-java.yml@main

